# Generated by Django 5.0.6 on 2024-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_shop', '0003_banner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('mainBanner', 'Main_Banner'), ('adBanner', 'Ad_Banner')], default='null', max_length=255),
        ),
    ]
