# Generated by Django 5.0.6 on 2024-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_shop', '0004_remove_banner_name_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('mainBanner', 'Main_Banner'), ('adBanner', 'Ad_Banner')], max_length=255),
        ),
    ]
